# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

basepath = "."

[env]
    l = "{l10n_base}/l10n/{locale}/"

[[paths]]
    reference = "l10n/templates/**"
    l10n = "{l}**"
